### ISSUE TITLE
Can't work on kodi 20.1

### ISSUE THREAD

**Issue by midozalouk** [tommistolercz/plugin.video.vk#113]
The plugin don't start in kodi 20.1 with the following error
![IMG_20230704_021905](https://github.com/tommistolercz/plugin.video.vk/assets/2486418/dd5fdfd4-86cf-4072-8adc-0ce787748a11)

**Comment by Akkari1988** [comment]
please fix it

**Comment by dima-glukhov** [comment]
не работает

**Comment by midenok** [comment]
Hi @tommistolercz! Are you going to fix this related to a blessed "cleanup" in https://github.com/xbmc/xbmc/pull/19301

````
2024-12-28 21:35:02.839 T:12240   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Administrator\AppData\Roaming\Kodi\addons\plugin.video.vk\resources\lib\addon.py", line 1846, in <module>
                                                       dispatch()
                                                     File "C:\Users\Administrator\AppData\Roaming\Kodi\addons\plugin.video.vk\resources\lib\addon.py", line 278, in dispatch
                                                       handler(**urlargs)
                                                     File "C:\Users\Administrator\AppData\Roaming\Kodi\addons\plugin.video.vk\resources\lib\addon.py", line 290, in listaddonmenu
                                                       db = tinydb.TinyDB(buildfp(FILENAME_DB))
                                                     File "C:\Users\Administrator\AppData\Roaming\Kodi\addons\plugin.video.vk\resources\lib\addon.py", line 207, in buildfp
                                                       fp = str(os.path.join(xbmc.translatePath(ADDON.getAddonInfo('profile')), filename))
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
                                                   
2024-12-28 21:35:02.872 T:8448    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.vk/
2024-12-28 21:35:02.888 T:8884    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vk/) failed
2024-12-28 21:35:09.486 T:9156    error <general>: Repository add-on repository.tommistolercz uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-12-28 21:35:09.486 T:9156    error <general>: Repository add-on repository.tommistolercz does not have any directory matching 21.1.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-12-28 21:35:09.490 T:9156    error <general>: Repository add-on repository.tommistolercz uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-12-28 21:35:09.490 T:9156    error <general>: Repository add-on repository.tommistolercz does not have any directory matching 21.1.0 and won't be able to update/serve addons! Please fix the addon.xml definition
```
